:mag::wrench: add missing header to use std::this_thread::sleep_for
Following the standard library used test_helpers.hpp fails compiling with :
```
test/test_helpers.hpp:175:27: error: no type named 'sleep_for' in  namespace 'std::this_thread'
  175 |         std::this_thread::sleep_for(retry_interval);
```

This happens on Ubuntu 22.04.5 LTS aarch64 for example with the default libstdc++
and g++ 11.4.0.